# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "acpi_call" ];

  # Wifi card not playing nice. Dunno why this works.
  #boot.blacklistedKernelModules = [ "iwlwifi" "iwlmvm" "mac80211" "cfg80211" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [ acpi_call ];
  systemd.services.mywifi = {
    path = with pkgs; [ kmod ];
    description = "load iwlwifi module after boot";
    script = ''rmmod iwlmvm iwlwifi mac80211 cfg80211; modprobe iwlwifi'';
    wantedBy = [ "multi-user.target" ];
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2d58d3da-7e49-4111-b812-a23c7f6b839a";
      fsType = "btrfs";
      options = [ "compress=zstd" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6FBE-7B6C";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/8ed9907d-201b-4c3c-8104-d7d09467eafc"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
